### ISSUE TITLE
Add evaluation pipeline

### ISSUE THREAD

**Issue by DianaDI** [DianaDI/compressedCV#23]

**Comment by hitanshsingla** [comment]
I just ran the evaluation pipeline after reading your wiki. It was pretty fast, Danke!
Had to install pycocotools before, but that was fine.

I used the following metric: WeightedPascalBoxes_PerformanceByCategory
Reason: weighed pascal can be used for imbalanced datasets, where the frequency of a particular object is much higher than another one.

Result for 'PassengerCar': 0.389629 @ 50% quality test jpg data
(This was just for my testing, hence not storing this in wiki)
