### ISSUE TITLE
Run training on gray scale images

### ISSUE THREAD

**Issue by DianaDI** [DianaDI/compressedCV#39]

**Comment by hitanshsingla** [comment]
Which quality?

**Comment by DianaDI** [comment]
> Which quality?

Right now on 40. Started with 40

**Comment by DianaDI** [comment]
I am converting original bmp images to grayscale then I run compression on them to avoid those colour artefacts on lower qualities. I'll start with 40 % quality.

**Comment by DianaDI** [comment]
Done (in PR, grayscale branch)
