### ISSUE TITLE
Write a report

### ISSUE THREAD

**Issue by DianaDI** [DianaDI/compressedCV#53]

**Comment by DianaDI** [comment]
Diana: intro, literature review, compression, the rest of the plots, transfer everything to latex, proof-reading
Hitansh: models description, experiments settings, description of plots with mAP, mAP normalised together with data storage size, future work, conclusion, proof-reading, env setup

**Comment by DianaDI** [comment]
upload report to repo

**Comment by DianaDI** [comment]
upload presentation to repo

**Comment by hitanshsingla** [comment]
Working on overleaf..

**Comment by DianaDI** [comment]
I will upload when we are done :)
