### ISSUE TITLE
Define and implement performance measures

### ISSUE THREAD

**Issue by DianaDI** [DianaDI/compressedCV#6]
- Accuracy: 1) ratio of detected objects  2) match % of overlap

**Comment by DianaDI** [comment]
Look at performance measures for Object Detection (e.g min avg precision )

**Comment by DianaDI** [comment]
@Otto-89 Do we need other measures other than mAP* (which uses IoU)? Now we use only mAP.

*https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173

**Comment by Otto-89** [comment]
> @Otto-89 Do we need other measures other than mAP* (which uses IoU)? Now we use only mAP.

I think using mAP only is fine to compare the performance of differently trained models.
But other metrics like AR or AP^[IoU=x] may help to get more detailed information about how the performance has changed.

Are you storing the model checkpoints? If so, these models can be evaluated with additional metrics any time later.
